### ISSUE TITLE
Time is out of dual 32-bit range

### ISSUE THREAD

**Issue by luccide** [ohm-ros-pkg/optris_drivers#18]
Hi, 

I am trying to use this package with Ros indigo on ubuntu 14.04, 
I am able to compile the package with catkin_make with no problems 
but when i try to run the imager node after about 5 seconds i get 

"terminate called after throwing an instance of 'std::runtime_error'
  what():  Time is out of dual 32-bit range"

Any suggestions ?

**Comment by melodybinbin** [comment]
@luccide @stefanmay 
Hi, I come across the same problem. How do you solve it? Thanks in advance!

**Comment by VictorLamoine** [comment]
This question has been asked on ROS Answer:
https://answers.ros.org/question/209452/exception-thrown-while-processing-service-call-time-is-out-of-dual-32-bit-range/

**Comment by Matesanz** [comment]
We had the same problem.
**Plugging the camera in and out** fixed it :sweat_smile:
