### ISSUE TITLE
how to use AO pin of PIF in linux

### ISSUE THREAD

**Issue by weichnn** [ohm-ros-pkg/optris_drivers#19]
Hi

The function of AO pin of PIF works well in window, but it cannot be used in linux and there is no information about it in document.

**Comment by stefanmay** [comment]
PIF AO is not supported by the IRImagerSDK, neither on Windows not on Linux. I guess you mean, that PIF AO is supported with PIConnect?

**Comment by weichnn** [comment]
thank you for your reply.

I know that, PIF AO is supported with connect SDK on windows.
But we need a solution to make this camera work on frame sync signal output with ROS or Linux. we want do time synchronization with other equipments like Vicon.
So, do you have any method make camera work on AO with frame sync signal output in ROS?
Thanks.

**Comment by stefanmay** [comment]
This is not a ROS related issue. The basic driver is maintained by Evocortex. Your demand needs to make an extension on this level. You should post your demand there: http://www.evocortex.com
So, I am closing this issue here.

**Comment by weichnn** [comment]
Can I ask another question?

We found that the camera only can be triggered with additional signal from PIF AI. 
This performance of time synchronization is only 8 Hz since we cannot find a preference make camera stop self image capturing. 
Am I right?

**Comment by stefanmay** [comment]
As I mentioned, these are not ROS related issues. Please post these questions to Evocortex.
