### ISSUE TITLE
Issue with installing on ubuntu 14.04, indigo 

### ISSUE THREAD

**Issue by AlisonBarnes** [ohm-ros-pkg/optris_drivers#20]
Hi, 

Have tried to get my optris 160 running on my 14.04 Ubuntu without success, have managed to get it working fine on Ubuntu 16.04 kinetic, but really need it to work on my 14.04. 

We have tried current groovy, fuerte branches and and pulling from the commit back in 2014 when @steevo87 got it working with Indigo. https://github.com/ohm-ros-pkg/optris_drivers/pull/7 Commit ID c92420c93ac9b33c5f35565a2228882bb81d1160

See attached error...

Cheers
Ali
![optris_error](https://user-images.githubusercontent.com/25995483/32262455-b860d2fc-bf0f-11e7-8a62-63c45e93e22a.png)

**Comment by stefanmay** [comment]
Dear Alison,
from your post, I just can see, that the process died and that there is a problem with UVC. These information are not enough to analyze the problem. Did you succeed in running the basic examples of the irDirectSDK (without ROS)? This is the first step in approaching the problem.
Best regards,
   Stefan May

**Comment by AlisonBarnes** [comment]
Hi stefanmay, 

Thanks for your response, I'm sorry, but I cant see the basic examples using the irDirectSDK, are they in here? http://documentation.evocortex.com/libirimager2/html/index.html
Somehow it is still got mayst in the file path when i'm launching...

Thanks in advance
Ali
